@startuml ActivityDiagram_OrderProcessing
!theme plain
title Диаграмма деятельности - Процесс оформления заказа

|Покупатель|
start
:Просмотр корзины;
:Нажать "Оформить заказ";

|Система|
:Проверить авторизацию;
if (Пользователь авторизован?) then (нет)
  |Покупатель|
  :Авторизация/Регистрация;
  |Система|
endif

:Отобразить форму заказа;

|Покупатель|
:Выбрать адрес доставки;
:Выбрать способ доставки;
:Выбрать способ оплаты;

|Система|
:Рассчитать стоимость доставки;
:Показать итоговую сумму;

|Покупатель|
if (Подтвердить заказ?) then (нет)
  :Внести изменения;
  |Система|
  :Пересчитать сумму;
else (да)
endif

|Система|
:Проверить наличие товаров;
if (Все товары в наличии?) then (нет)
  :Уведомить о недоступных товарах;
  |Покупатель|
  :Удалить/заменить товары;
  |Система|
else (да)
endif

:Создать заказ;
:Зарезервировать товары;

if (Способ оплаты онлайн?) then (да)
  :Обработать платеж;
  if (Платеж успешен?) then (нет)
    :Отменить резервирование;
    :Уведомить об ошибке;
    |Покупатель|
    :Выбрать другой способ оплаты;
    |Система|
  else (да)
  endif
endif

:Отправить подтверждение на email;
:Передать заказ в обработку;

|Покупатель|
:Получить подтверждение;
stop

@enduml
